// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestV.Data;

#nullable disable

namespace TestV.Migrations
{
    [DbContext(typeof(TestVContext))]
    partial class TestVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TestV.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<decimal>("dcSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dtHire")
                        .HasColumnType("datetime2");

                    b.Property<int>("intPhone")
                        .HasColumnType("int");

                    b.Property<string>("vcAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vcEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vcName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
